<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;

class AppTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // User
        $storeavatar = storage_path('app/public/app_user/').'avatar';
        if(!File::exists($storeavatar)){
            File::makeDirectory($storeavatar, 0777, true);
        }
        $users = [
            [
                'nik' => '9000901',
                'name' => 'ADMINISTRATOR',
                'dept_id' => null,
                'position_id' => null,
                'group_id' => null,
                'avatar' => null,
                'active' => 1,
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00',
            ]
        ];
        DB::table('app_users')->insert($users);

        // User Login
        $userslogin = [
            [
                'nik' => 9000901,
                's_nik' => '901',
                'email' => 'admin@molindointigas.co.id',
                'password' => Hash::make('password'),
                'active' => 1,
                'admin' => 1,
                'created_at' => '2022-03-01 07:01:01',
                'updated_at' => '2022-03-01 07:01:01',
            ]
        ];
        DB::table('app_user_logins')->insert($userslogin);

        // Dept List
        $departments = [
            [
                "id" => 1,
                "name" => "CORPORATE",
                "parent_id" => null,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00"
            ],
            [
                "id" => 2,
                "name" => "PLANT",
                "parent_id" => null,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00"
            ],
            [
                "id" => 3,
                "name" => "SALES (WEST)",
                "parent_id" => null,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00"
            ],
            [
                "id" => 4,
                "name" => "SALES (EAST)",
                "parent_id" => null,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00"
            ],
            [
                "id" => 5,
                "name" => "LOGISTIC",
                "parent_id" => null,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00"
            ],
            [
                "id" => 6,
                "name" => "MANAGEMENT SYSTEM",
                "parent_id" => null,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00"
            ],
            [
                "id" => 7,
                "name" => "FAT",
                "parent_id" => null,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00"
            ],
            [
                "id" => 8,
                "name" => "HRM&GA",
                "parent_id" => null,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00"
            ],
        ];
        DB::table('app_hr_departments')->insert($departments);

        // Position List
        $positions = [
            [
                "id" => 1,
                "parent_id" => NULL,
                "name" => "Root",
                "dept_id" => NULL,
                "sub_dept_id" => NULL,
                "level" => 1,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 2,
                "parent_id" => 58,
                "name" => "PLANT MANAGER",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 4,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 3,
                "parent_id" => 2,
                "name" => "QC SUPERVISOR",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 4,
                "parent_id" => 2,
                "name" => "UTILITY SUPERVISOR",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 5,
                "parent_id" => 2,
                "name" => "PRODUCTION SUPERVISOR",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 6,
                "parent_id" => 2,
                "name" => "TECHNICAL DESIGN OFFICER",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 7,
                "parent_id" => 3,
                "name" => "QUALITY CONTROL STAFF",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 8,
                "parent_id" => 4,
                "name" => "UTILITY WELDER STAFF",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 9,
                "parent_id" => 4,
                "name" => "UTILITY OPR. STAFF",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 10,
                "parent_id" => 4,
                "name" => "UTILITY SUPPORT STAFF",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 11,
                "parent_id" => 5,
                "name" => "DRYICE PROD. OPR. STAFF",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 12,
                "parent_id" => 5,
                "name" => "CO2 PROD. OPR. STAFF",
                "dept_id" => 2,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 13,
                "parent_id" => 58,
                "name" => "SALES MANAGER (WEST)",
                "dept_id" => 3,
                "sub_dept_id" => NULL,
                "level" => 4,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 14,
                "parent_id" => 13,
                "name" => "SALES OPERATION SUPERVISOR",
                "dept_id" => 3,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 15,
                "parent_id" => 14,
                "name" => "GEN. ADMINISTRATION STAFF",
                "dept_id" => 3,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 16,
                "parent_id" => 14,
                "name" => "HSE & TECHNICAL SUPPORT STAFF",
                "dept_id" => 3,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 17,
                "parent_id" => 14,
                "name" => "QC & INVENTORY STAFF",
                "dept_id" => 3,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 18,
                "parent_id" => 14,
                "name" => "TRANSPORTER DRIVER",
                "dept_id" => 3,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 19,
                "parent_id" => 58,
                "name" => "SALES MANAGER (EAST)",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 4,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 20,
                "parent_id" => 19,
                "name" => "SALES SUPERVISOR",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 21,
                "parent_id" => 19,
                "name" => "DISTRIBUTION OPR. SUPERVISOR",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 22,
                "parent_id" => 20,
                "name" => "SALES STAFF",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 23,
                "parent_id" => 20,
                "name" => "SALES ADM. STAFF",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 24,
                "parent_id" => 20,
                "name" => "TECHNICAL SUPPORT",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 25,
                "parent_id" => 21,
                "name" => "TRANSPORTER MECHANICAL STAFF",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 26,
                "parent_id" => 21,
                "name" => "REGULAR DRIVER",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 27,
                "parent_id" => 21,
                "name" => "TRANSPORTER DRIVER",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 28,
                "parent_id" => 21,
                "name" => "TRANSPORTER CO-DRIVER",
                "dept_id" => 4,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 29,
                "parent_id" => 58,
                "name" => "LOGISTIC MANAGER",
                "dept_id" => 5,
                "sub_dept_id" => NULL,
                "level" => 4,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 30,
                "parent_id" => 29,
                "name" => "PURCHASING SUPERVISOR",
                "dept_id" => 5,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 31,
                "parent_id" => 29,
                "name" => "WAREHOUSE SUPERVISOR",
                "dept_id" => 5,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 32,
                "parent_id" => 30,
                "name" => "PURCHASING STAFF",
                "dept_id" => 5,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 33,
                "parent_id" => 31,
                "name" => "WAREHOUSE STAFF",
                "dept_id" => 5,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 34,
                "parent_id" => 58,
                "name" => "MANAGEMENT SYSTEM MANAGER",
                "dept_id" => 6,
                "sub_dept_id" => NULL,
                "level" => 4,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 35,
                "parent_id" => 34,
                "name" => "QUALITY SYSTEM OFFICER",
                "dept_id" => 6,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 36,
                "parent_id" => 34,
                "name" => "HSE OFFICER",
                "dept_id" => 6,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 37,
                "parent_id" => 58,
                "name" => "FINANCE ACCOUNTING & TAX MANAGER",
                "dept_id" => 7,
                "sub_dept_id" => NULL,
                "level" => 4,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 38,
                "parent_id" => 37,
                "name" => "FINANCE ACCOUNTING & TAX SUPERVISOR",
                "dept_id" => 7,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 39,
                "parent_id" => 38,
                "name" => "ACCOUNT RECEIVEABLE (AR) STAFF",
                "dept_id" => 7,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 40,
                "parent_id" => 38,
                "name" => "FINANCE STAFF",
                "dept_id" => 7,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 41,
                "parent_id" => 38,
                "name" => "ACCOUNT PAYABLE (AP) STAFF",
                "dept_id" => 7,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 42,
                "parent_id" => 38,
                "name" => "CONTROLLER STAFF",
                "dept_id" => 7,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 43,
                "parent_id" => 38,
                "name" => "CASHIER STAFF",
                "dept_id" => 7,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 44,
                "parent_id" => 58,
                "name" => "HRM & GA MANAGER",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 4,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 45,
                "parent_id" => 44,
                "name" => "HRM SUPERVISOR",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 46,
                "parent_id" => 44,
                "name" => "GA SUPERVISOR",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 47,
                "parent_id" => 44,
                "name" => "IT SUPERVISOR",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 48,
                "parent_id" => 44,
                "name" => "SENIOR SECURITY",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 5,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 49,
                "parent_id" => 45,
                "name" => "HRM STAFF",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 50,
                "parent_id" => 46,
                "name" => "CORPORATE AFFAIR STAFF",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 51,
                "parent_id" => 46,
                "name" => "GENERAL AFFAIR STAFF",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 52,
                "parent_id" => 46,
                "name" => "PLANT HOUSEKEEPING STAFF",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 53,
                "parent_id" => 46,
                "name" => "OFFICE HOUSEKEEPING STAFF",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 54,
                "parent_id" => 46,
                "name" => "BOD/BOC DRIVER",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 55,
                "parent_id" => 47,
                "name" => "IT STAFF",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 56,
                "parent_id" => 48,
                "name" => "SECURITY STAFF",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 57,
                "parent_id" => 1,
                "name" => "DIRECTOR",
                "dept_id" => 1,
                "sub_dept_id" => NULL,
                "level" => 2,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 58,
                "parent_id" => 57,
                "name" => "GENERAL MANAGER",
                "dept_id" => 1,
                "sub_dept_id" => NULL,
                "level" => 3,
                "user_id" => NULL,
                "created_at" => "2022-07-25 13:00:00",
                "updated_at" => "2022-07-25 13:00:00",
            ],
            [
                "id" => 59,
                "parent_id" => 47,
                "name" => "IT SENIOR STAFF",
                "dept_id" => 8,
                "sub_dept_id" => NULL,
                "level" => 6,
                "user_id" => NULL,
                "created_at" => "2022-11-04 08:00:00",
                "updated_at" => "2022-11-04 08:00:00",
            ],
        ];
        DB::table('app_hr_positions')->insert($positions);

        // Permissions List
        $permissions = [
            [
                'id' => 1, 
                'name' => 'manage.all',
                'guard_name' => 'web',
                'description' => 'Semua Akses App',
                'text' => '*',
                'group_name' => 'WildCard', 
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00' 
            ],
            [
                'id' => 2, 
                'name' => 'read.Auth',
                'guard_name' => 'web',
                'description' => 'Akses App tanpa otorisasi',
                'text' => 'App',
                'group_name' => 'General',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 3, 
                'name' => 'read.ACL',
                'guard_name' => 'web',
                'description' => 'Akses App dengan otorisasi',
                'text' => 'App Auth',
                'group_name' => 'General', 
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 4, 
                'name' => 'read.AppTodo',
                'guard_name' => 'web',
                'description' => 'Akses masuk AppTodo',
                'text' => 'AppTodo Access',
                'group_name' => 'AppTodo',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
                ['id' => 5, 
                'name' => 'create.AppTodo',
                'guard_name' => 'web',
                'description' => 'Akses membuat Task',
                'text' => 'AppTodo Create',
                'group_name' => 'AppTodo',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'],
            [
                'id' => 6, 
                'name' => 'read.AppPhoneExt',
                'guard_name' => 'web',
                'description' => 'Akses aplikasi phonebook internal',
                'text' => 'AppPhoneExtension Access',
                'group_name' => 'AppPhoneExtension',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 7, 
                'name' => 'create.AppPhoneExt',
                'guard_name' => 'web',
                'description' => 'Akses tambah data phonebook internal',
                'text' => 'AppPhoneExtension Create',
                'group_name' => 'AppPhoneExtension',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 8, 
                'name' => 'edit.AppPhoneExt',
                'guard_name' => 'web',
                'description' => 'Akses update data phonebook internal',
                'text' => 'AppPhoneExtension Edit',
                'group_name' => 'AppPhoneExtension',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 9, 
                'name' => 'delete.AppPhoneExt',
                'guard_name' => 'web',
                'description' => 'Akses hapus data phonebook internal',
                'text' => 'AppPhoneExtension Delete',
                'group_name' => 'AppPhoneExtension',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'],
            [
                'id' => 10,
                'name' =>  'read.AppPhonebook',
                'guard_name' => 'web',
                'description' => 'Akses aplikasi phonebook eksternal',
                'text' => 'AppPhonebook Access',
                'group_name' => 'AppPhonebook',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'],
            [
                'id' => 11,
                'name' =>  'create.AppPhonebook',
                'guard_name' => 'web',
                'description' => 'Akses tambah data phonebook eksternal',
                'text' => 'AppPhonebook Create',
                'group_name' => 'AppPhonebook',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
                ['id' => 12,
                'name' =>  'edit.AppPhonebook',
                'guard_name' => 'web',
                'description' => 'Akses update data phonebook eksternal',
                'text' => 'AppPhonebook Edit',
                'group_name' => 'AppPhonebook',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 13,
                'name' =>  'read.AppDelivery',
                'guard_name' => 'web',
                'description' => 'Akses aplikasi surat jalan',
                'text' => 'AppDelivery Access',
                'group_name' => 'AppDelivery',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'],
            [
                'id' => 14,
                'name' =>  'create.AppDelivery',
                'guard_name' => 'web',
                'description' => 'Akses input data surat jalan',
                'text' => 'AppDelivery Create',
                'group_name' => 'AppDelivery',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 15,
                'name' =>  'edit.AppDelivery',
                'guard_name' => 'web',
                'description' => 'Akses update data surat jalan',
                'text' => 'AppDelivery Update',
                'group_name' => 'AppDelivery',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'],
            [
                'id' => 16,
                'name' =>  'invoice.AppDelivery',
                'guard_name' => 'web',
                'description' => 'Akses update invoice data surat jalan',
                'text' => 'AppDelivery Post Invoice',
                'group_name' => 'AppDelivery',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 17,
                'name' =>  'read.AppInventaris',
                'guard_name' => 'web',
                'description' => 'Akses aplikasi inventaris',
                'text' => 'AppInventaris Access',
                'group_name' => 'AppInventaris',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 18,
                'name' =>  'create.AppInventaris',
                'guard_name' => 'web',
                'description' => 'Akses input data inventaris',
                'text' => 'AppInventaris Create',
                'group_name' => 'AppInventaris',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 19,
                'name' =>  'edit.AppInventaris',
                'guard_name' => 'web',
                'description' => 'Akses update data inventaris',
                'text' => 'AppInventaris Update',
                'group_name' => 'AppInventaris',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            
            [
                'id' => 20,
                'name' =>  'archieve.AppInventaris',
                'guard_name' => 'web',
                'description' => "Akses 'tandai di gudang' untuk barang",
                'text' => 'AppInventaris Archieve Goods',
                'group_name' => 'AppInventaris',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 21,
                'name' =>  'sell.AppInventaris',
                'guard_name' => 'web',
                'description' => "Akses 'tandai di jual' untuk barang",
                'text' => 'AppInventaris Sell Goods',
                'group_name' => 'AppInventaris',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 22,
                'name' =>  'export.AppInventaris',
                'guard_name' => 'web',
                'description' => 'Akses print dan export QR atau List Data',
                'text' => 'AppInventaris Print Qr & List',
                'group_name' => 'AppInventaris',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 23,
                'name' =>  'read.AppUserMgt',
                'guard_name' => 'web',
                'description' => 'Akses aplikasi User Management',
                'text' => 'AppUserManagement Access',
                'group_name' => 'AppUserManagement',
                'created_at' =>'2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 24,
                'name' =>  'create.AppUserMgt',
                'guard_name' => 'web',
                'description' => 'Akses input data user',
                'text' => 'AppUserManagement Create',
                'group_name' => 'AppUserManagement',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 25,
                'name' =>  'switchlogin.AppUserMgt',
                'guard_name' => 'web',
                'description' => 'Akses switch on/off Login User',
                'text' => 'AppUserManagement Switch Login',
                'group_name' => 'AppUserManagement',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 26,
                'name' =>  'switchuser.AppUserMgt',
                'guard_name' => 'web',
                'description' => 'Akses switch aktif/non-aktif User',
                'text' => 'AppUserManagement Switch User',
                'group_name' => 'AppUserManagement',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 27,
                'name' =>  'edit.AppUserMgt',
                'guard_name' => 'web',
                'description' => 'Akses Update data user',
                'text' => 'AppUserManagement Update',
                'group_name' => 'AppUserManagement',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 28,
                'name' =>  'editinfo.AppUserMgt',
                'guard_name' => 'web',
                'description' => 'Akses Update Info User',
                'text' => 'AppUserManagement Update Info-User',
                'group_name' => 'AppUserManagement',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 29,
                'name' =>  'editaccount.AppUserMgt',
                'guard_name' => 'web',
                'description' => 'Akses Update Account User',
                'text' => 'AppUserManagement Update Info-Account',
                'group_name' => 'AppUserManagement',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 30,
                'name' =>  'editpermission.AppUserMgt',
                'guard_name' => 'web',
                'description' => 'Akses Update Permission User',
                'text' => 'AppUserManagement Update Info-Permission',
                'group_name' => 'AppUserManagement',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 31,
                'name' =>  'resetpassuser.AppUserMgt',
                'guard_name' => 'web',
                'description' => 'Akses Reset Account User',
                'text' => 'AppUserManagement Reset Password User',
                'group_name' => 'AppUserManagement',
                'created_at' => '2022-07-11 07:00:00',
                'updated_at' => '2022-07-11 07:00:00'
            ],
            [
                'id' => 32,
                'name' =>  'export.AppDelivery',
                'guard_name' => 'web',
                'description' => 'Akses Ekspor Data Surat Jalan ke XLSX',
                'text' => 'AppDelivery Export',
                'group_name' => 'AppDelivery',
                'created_at' => '2022-08-18 07:00:00',
                'updated_at' => '2022-08-18 07:00:00'
            ],
            [
                'id' => 33,
                'name' =>  'delete.AppPhonebook',
                'guard_name' => 'web',
                'description' => 'Akses update data phonebook eksternal',
                'text' => 'AppPhonebook Delete',
                'group_name' => 'AppPhonebook',
                'created_at' => '2022-09-11 07:00:00',
                'updated_at' => '2022-09-11 07:00:00'
            ],
            [
                'id' => 34,
                'name' =>  'read.AppHRPresence',
                'guard_name' => 'web',
                'description' => 'Akses HR - Monitoring Absensi',
                'text' => 'AppHR Presence',
                'group_name' => 'AppHR',
                'created_at' => '2022-11-30 11:00:00',
                'updated_at' => '2022-11-30 11:00:00'
            ],
            [
                'id' => 35,
                'name' =>  'read.AppHRPosition',
                'guard_name' => 'web',
                'description' => 'Akses HR - Jabatan Karyawan',
                'text' => 'AppHR Position',
                'group_name' => 'AppHR',
                'created_at' => '2022-11-30 11:00:00',
                'updated_at' => '2022-11-30 11:00:00'
            ],
            [
                'id' => 36,
                'name' =>  'edit.AppHRPosition',
                'guard_name' => 'web',
                'description' => 'Akses HR - Edit Jabatan Karyawan',
                'text' => 'AppHR Position Edit',
                'group_name' => 'AppHR',
                'created_at' => '2022-11-30 11:00:00',
                'updated_at' => '2022-11-30 11:00:00'
            ],
        ];
        DB::table('app_rp_permissions')->insert($permissions);

        // User Permissions
        $userpermissions = [
            [
                'permission_id' => 1,
                'model_type' => "App\\Models\\API\\Auth\\AppUserLogin",
                'user_nik' => '9000901'
            ]
        ];
        DB::table('app_rp_model_has_permissions')->insert($userpermissions);

    }
}
